### ISSUE TITLE
html_stream wording suggests multiple .loud elements

### ISSUE THREAD

**Issue by max** [workshopper/stream-adventure#105]
I was trying to come up with a solution that would uppercase multiple `.loud` elements in any given HTML input. That proved to be quite a bit more difficult than simply transforming a single element. Perhaps the problem statement can be reworded [here](https://github.com/substack/stream-adventure/blob/master/problems/html_stream/problem.txt#L2).

**Comment by Noyabronok** [comment]
I absolutely agree. Was going to make the same suggestion.  The example solution only uppercases the first matching element, and the input html only has a single loud class to test with.

**Comment by swinston100** [comment]
Yes I also noticed this and agree!

Being adventurous, I wrote to try and handle for multiple elements. But, when I add another .loud element to the HTML input it fails with **Error: write after end** when it tries to transform the second element.

```js
var trumpet = require('trumpet');
var through = require('through2');


var upperCase = function(buffer, enc, next){
  this.push(buffer.toString().toUpperCase());
  next();
}
var upperStream = through(upperCase); //create a transform stream for upperCase

var tr = trumpet(); //create new trumpet stream
process.stdin.pipe(tr); //pipe the input into trumpet

//find elements and transform them
tr.selectAll('.loud', function (elem){

var rs = elem.createReadStream();
var ws = elem.createWriteStream();

rs.pipe(upperStream).pipe(ws); //transform the stream

});

tr.pipe(process.stdout); //pipe trumpet back to output

```

@max, if can you please help me by pointing out how I can fix to handle all the elements?
Thanks

**Comment by swinston100** [comment]
@max - all good I figured it out - I need to move the deceleration of upperStream and upperCase function into the selectAll event handler.

Corrected code:

```js
var trumpet = require('trumpet');
var through = require('through2');



var tr = trumpet(); //create new trumpet stree

process.stdin.pipe(tr); //pipe the input into trumpet

//find elements and transform them
tr.selectAll('.loud', function (elem){

  var upperCase = function(buffer, enc, next){
    this.push(buffer.toString().toUpperCase());
    next();
  }
  var upperStream = through(upperCase); //create a transform stream for upperCase

  var rs = elem.createReadStream();
  var ws = elem.createWriteStream();

  rs.pipe(upperStream).pipe(ws); //transform the stream

});

tr.pipe(process.stdout); //pipe trumpet back to output

```

**Comment by kalinchernev** [comment]
This discussion could be complemented by 3 pull requests doing basically the same as suggested:
- Update problems/html_stream/solution.js #69
- Changing html_stream to use selectAll instead of select #103
- html_stream, support for multiple 'loud' tags #146

Although #69 should be picked as a primary change request being first, #146 looks most thorough, readable and it's the only pull request with no conflicts at the moment.

**Comment by ccarruitero** [comment]
I'm closing since this it's stale from some time ago. We are planning to update `html_stream` removing trumpet dependency, join the conversation in #239.
