### ISSUE TITLE
Lesson 1 doesn't exit on fail

### ISSUE THREAD

**Issue by Sequoia** [workshopper/stream-adventure#124]
```
$ stream-adventure verify

TAP version 13
# (anonymous)
not ok 1 stream-adventure verify YOURFILE.js
  ---
    operator: equal
    expected: 1
    actual:   0
    at: Test.<anonymous> (/Users/sequoia/.npm-packages/lib/node_modules/stream-adventure/node_modules/adventure-verify/index.js:48:40)



kjhlkjsadf
^C
```

**Comment by calvinmetcalf** [comment]
can you do a node -v to tell me what version of node you are using? for me a ctrl-c closes it

**Comment by Ntangen** [comment]
You need to specify the program file you're verifying: "stream-adventure verify program.js" (assuming program.js is your program file). 

Should your program hang for some reason, CTRL-C should kill it.

**Comment by kalinchernev** [comment]
I'd close this issue for the moment as the feedback from the console is indeed `stream-adventure verify YOURFILE.js` as @Ntangen suggests.
@Sequoia feel free to comment should you have a different opinion.
