### ISSUE TITLE
LINES challenge dubugging difficulty

### ISSUE THREAD

**Issue by ajfarkas** [workshopper/stream-adventure#132]
I found a correct solution to this challenge (which passed `verify`), but since I was debugging using `run` I thought I had an error: 
The actual output of the correct solution is a single, lowercase paragraph. This makes debugging maddening. Is there a better `run` test so NodeStudents can see what their code is doing?

**Comment by rykerrumsey** [comment]
+1 on this. Cut and pasted solution.js directly into my program.js file and the output from 
<code>stream-adventure run program.js</code> was 


<code>riverrun, past eve and adam's, from swerve of shore to bend of bay, brings us by a commodius vicus of recirculation back to    howth castle and environs. sir tristram, violer d'amores, fr'over the short sea, had passen- core rearrived from north armorica on this side the scraggyisthmus of europe minor to wielderfight his penisolate war: nor    had topsawyer's rocks by the stream oconee exaggerated themselse   to laurens county's gorgios while they went doublin their mumper   all the time: nor avoice from afire bellowsed mishe mishe to   tauftauf thuartpeatrick: not yet, though venissoon after, had a   kidscad buttended a bland old isaac: not yet, though all's fair in    vanessy, were sosie sesthers wroth with twone nathandjoe. rot a   peck of pa's malt had jhem or shen brewed by arclight and rory    end to the regginbrow was to be seen ringsome on the aquaface.</code>

**Comment by simonsmith** [comment]
I found I could only pass it without using `split`, otherwise I was given one single string

**Comment by kalinchernev** [comment]
Closing this one as #140 is merged with positive feedback.
Feel free to re-open in case further work is needed.
