### ISSUE TITLE
concat #6 instructions could improve

### ISSUE THREAD

**Issue by curioussavage** [workshopper/stream-adventure#133]
I was a little confused on this one, saw this issue: [819](https://github.com/nodeschool/discussions/issues/819) in the discussions repo where the only person to help declared that the instructions were "fairly clear to me" lol.

With that aside I think what is not clear is how to get data from the callback provided to concat-stream to stdout. In the previous exercise we were told to use the through2 module, it was demonstrated that you need to use `this.push(data);` then `next()` then we can  `.pipe(process.stdout)` to get the data there. So the student is used to the pattern of piping data to stdout.

I am pretty sure the `write()` method of stdout was not used or mentioned before this point and it is unreasonable to expect beginners to think of checking docs on `process.stdout` to find that. I believe the method should be mentioned in the instructions

**Comment by Ryan1729** [comment]
#48 also suggests that this question could use some rewriting.

**Comment by Johnbastian** [comment]
+1
I started the concat tutorial and was completely lost in regards to the output. The instruction says "Buffer the text and reverse it using the `concat-stream` module before writing it to stdout", but I had no idea how to pass the results to stdout. 
The solution on the repo uses console.log to do it, but I had no idea that Node.js used process.stdout.write to perform the console.log function... I found it out later on SO. Heck, I didn't even know there was a write function for stdout. Please mention process.stdout.write() exists for direct output.

**Comment by patrickjkennedy** [comment]
I had this issue myself today when I was working the problem. I think if you mentioned that concat-stream is only readable and you can't pipe to stdout like the previous examples it would help. Maybe include an example of using process.stdout.write() in the description too.

**Comment by ccarruitero** [comment]
I'm closing this since concat problem description was updated in https://github.com/workshopper/stream-adventure/commit/6bcb76793e5fb2c5231c5e45d69afe3a55c9cf82 and there will be an exercise about writable streams (#240) for complement the doubts about that.
