### ISSUE TITLE
Exercise 7 instructions refresher uses 'through' instead of 'through2'

### ISSUE THREAD

**Issue by seppevs** [workshopper/stream-adventure#151]
I have noticed that all exercises were recently (?) updated with 'through2' where previously 'through' was used.

But in exercise 7, the instructions still mention the older 'through' module again:

> As a refresher, here's an example with the default through callbacks explicitly
> defined:
> 
>    var through = require('through')
>    process.stdin.pipe(through(write, end)).pipe(process.stdout);
> 
>    function write (buf) { this.queue(buf) }
>    function end () { this.queue(null)
> 
> Do that, but send upper-case data in your http server in response to POST data.
> 
> Make sure to `npm install through` in the directory where your solution file
> lives.

I think these instructions need to be updated with a refresher for through2 instead of through. Especially because all previous exercises use through2 and through2 is event used in the reference solution of this exercise:

``` javascript
// Here's the reference solution:

  var http = require('http');
  var through = require('through2');

  var server = http.createServer(function (req, res) {
      if (req.method === 'POST') {
          req.pipe(through(function (buf, _, next) {
              this.push(buf.toString().toUpperCase());
              next();
          })).pipe(res);
      }
      else res.end('send me a POST\n');
  });
  server.listen(parseInt(process.argv[2]));
```

**Comment by kalinchernev** [comment]
Checking current version of the problem definition in master, it's [using through2 as requested](https://github.com/workshopper/stream-adventure/blob/master/problems/http_server/problem.txt#L44).
The [change has been applied before](https://github.com/workshopper/stream-adventure/commit/235ee96dd4a5d53be67365fae39669e216e55236#diff-bdbad25c4cc864da8358d53609f4b710) this issue being open.
@seppevs please `npm update` to get latest version and it should be ok.
