### ISSUE TITLE
Lesson #6 concat not working

### ISSUE THREAD

**Issue by cirpo** [workshopper/stream-adventure#153]
node version 0.12.7

I also tried the provided solution but `stream-adventure verify` is failing. 
Launching the script and inserting some random input in the shell I get no output.

if I run `echo "helo world" | node program.js` it works, why?

**Comment by cirpo** [comment]
ok, I found the reason why just `echo "helo world" | node program.js` is working: concat is waiting for the stdin to be closed, that's why is not working just launching  the script and typing in the shell.
But then, why the tests are not passing? Was it a valid behaviour in the previous nodejs versions?

**Comment by marcoslhc** [comment]
It is passing for me.

**Comment by kalinchernev** [comment]
@cirpo could you please paste in here the output you get for the problem not passing?

**Comment by ccarruitero** [comment]
Closing since is stale and cannot be reproduced
