### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by syzer** [workshopper/stream-adventure#160]
in the `websockets` solution there is an error, with the node 4+

``` js
TypeError: dest.on is not a function 
dest.on('drain', ondrain);
```

index.js on like 65
on node 0.10 solution was working ok.

**Comment by bengovernment** [comment]
I have the exact same issue in node 4.4.0... Just gonna skip the lesson :)

**Comment by bengovernment** [comment]
Here's an alternate solution with simple websocket that will get you that warm fuzzy 100% completion feeling.

```javascript
vr sws = require('simple-websocket');
 
var socket = new sws('ws://localhost:8099');
socket.on('connect', function () {
  socket.send('hello\n');
})
```

**Comment by ccarruitero** [comment]
This problem was because the old verify process (`bin/verify`). That was replaced with [`adventure-verify`](https://www.npmjs.com/package/adventure-verify) module later. And not we move to use [`workshopper-exercise`](https://www.npmjs.com/package/workshopper-exercise)
