### ISSUE TITLE
Why do the author of this workshop encourage to use third party modules for beginners?

### ISSUE THREAD

**Issue by segmentationfaulter** [workshopper/stream-adventure#162]
I am new to learning node and I was attempting this workshop. I noticed that at most of the occasions author asks to go and attempt the challenges using third party modules from npm registry when a given challenge can be very well attempted using node's core modules. I was wondering if it is a bad practice for a beginner to rely too much on third party modules, shouldn't the one who is beginning his/her journey with node try to learn node core?
P.S: I am making assuming that the one who is attempting this workshop is a beginner with node, in most of the cases.

**Comment by paulkernfeld** [comment]
Hi @segmentationfaulter, I'm not a node expert but I can attempt to answer this question. I think it depends on the level of abstraction that you're interested in learning about. If you want to learn about node's core APIs, then by all means, implementing your own streaming libraries sounds like a great way to do it! I really like the title of this Coding Horror article: "[Don't Reinvent The Wheel, Unless You Plan on Learning More About Wheels](http://blog.codinghorror.com/dont-reinvent-the-wheel-unless-you-plan-on-learning-more-about-wheels/)."

Stream-adventure seems to be about learning to use node streams and common streaming libraries in an idiomatic way. Of course, you could go even lower by hacking on node itself, and you can go higher by using a streaming framework. However, I think that this is a pretty reasonable level of abstraction for a lot of projects. Additionally, compared to other languages, [node](http://blog.nodejitsu.com/the-nodejs-philosophy/) and [node modules](http://substack.net/how_I_write_modules) are conventionally kept small, which means that a typical node project will need to use a lot of modules. So maybe learning to use a lot of modules is a good introduction to the node philosophy!

**Comment by kalinchernev** [comment]
I'm closing this one for now as @paulkernfeld is giving a good reply.
It's not only in node that developers re-use existing solutions from early stage.
@segmentationfaulter please feel free to re-open if you feel there's something to do or suggest here?
