### ISSUE TITLE
Websockets not passing referenced solutions

### ISSUE THREAD

**Issue by colindevs** [workshopper/stream-adventure#164]
I tried on my own, it didn't work. So I looked up the solution. Still didn't work.
Tried these ->
Solution in [solution.js](https://github.com/substack/stream-adventure/blob/master/problems/websockets/solution.js):

```
var ws = require('websocket-stream');
var stream = ws('ws://localhost:8099');
stream.write('hello\n');
```

Solution mentioned by other issues:

```
var ws = require('websocket-stream');
var stream = ws('ws://localhost:8099');
stream.end('hello\n');
```

Both solutions gave the same error in the console: 

```
TAP version 13
################################################
#                                              #
# Open http://localhost:8099 to run your code! #
#                                              #
################################################

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################


# (anonymous)

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '/Users/colin/Desktop/streams.js' from '/Users/colin/Desktop'
    at /usr/local/lib/node_modules/stream-adventure/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/stream-adventure/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/stream-adventure/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/stream-adventure/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by jfloresremar** [comment]
Colindevs, i had a similar problem.
I cannot explain the reason but i solved this problem doing this:
1. Install stream-adventure again: npm install -g stream-adventure
2. remove node_modules folder where you have your solution.js (i deleted package.json too)
that's all

**Comment by colindevs** [comment]
@jfloresremar thanks, I'll try it.

**Comment by enderandpeter** [comment]
I am also running into a similar program going through the Websockets chapter of the stream-adventure tutorial on a Windows 10 computer running node.js version 5.3.0. When visiting http://localhost:8099, it reports the following failure to find what looks like the is-buffer module:

    Error: Cannot find module './c:/Users/me/AppData/Roaming/npm/node_modules/stream-adventure/node_modules/is-buffer/index.js' from 'i:\Dropbox\Dropbox\stream-adventure\09_Websockets\node_modules\co
re-util-is\lib'

I tried install stream-adventure globally again, removing the node_modules folder, running global and then local modules for `is-buffer`, `bufferutil`, and `websocket-stream`, but to no avail. It only wants a local version of `websocket-stream`, it looks like.

When I do the tutorial and instructed in OS X and Linux in the same node version, the websocket server runs with no issue. Only in Windows do I get the above error. I can't tell if it's a Windows issue or something about local vs. global, or both.

**Comment by HermantNET** [comment]
I am also getting this issue on windows and have tried all fixes mentioned in this thread, alas to no avail.

**Comment by ccarruitero** [comment]
This problem was because the old verify process (`bin/verify`). That was replaced with [`adventure-verify`](https://www.npmjs.com/package/adventure-verify) module later. And not we move to use [`workshopper-exercise`](https://www.npmjs.com/package/workshopper-exercise)
