### ISSUE TITLE
same solution with differents variable's name. why my solution is wrong?

### ISSUE THREAD

**Issue by ghost** [workshopper/stream-adventure#169]
________my solution_________
var concat = require('concat-stream');
process.stdin.pipe(concat(function(buf){
    var output =buf.toString().split('').reverse().join('');
    console.log(output);
}));
___________ official solution ____________

var concat = require('concat-stream');
  process.stdin.pipe(concat(function (src) {
      var s = src.toString().split('').reverse().join('');
      console.log(s);
  }));

**Comment by paulkernfeld** [comment]
@CarlKk does the official solution work if you copy/paste it verbatim?

**Comment by kalinchernev** [comment]
Tested both solutions are working fine for me.

**Comment by ccarruitero** [comment]
Closing since it's stale from a lot of time ago
