### ISSUE TITLE
WEBSOCKETS Fails verifying

### ISSUE THREAD

**Issue by carloscarvallo** [workshopper/stream-adventure#174]
The same thing happen with the prev adventure HTTPClient
![](http://i.imgur.com/9H9BAZR.png)

```
$ stream-adventure solution
// Here's the reference solution:

  var ws = require('websocket-stream');
  var stream = ws('ws://localhost:8099');
  stream.write('hello\n');

$ stream-adventure verify stream-adventure/9_app.js

TAP version 13
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################


$ more stream-adventure/9_app.js
var ws = require('websocket-stream');
var stream = ws('ws://localhost:8099');
stream.write('hello\n');
```

**Comment by geekydatamonkey** [comment]
I just ran into a similar issue. But I realized that I forgot to install `websocket-stream`. 😊 

`npm install --save websocket-stream`

**Comment by ccarruitero** [comment]
This problem was because the old verify process (`bin/verify`). That was replaced with [`adventure-verify`](https://www.npmjs.com/package/adventure-verify) module later. And not we move to use [`workshopper-exercise`](https://www.npmjs.com/package/workshopper-exercise)
