### ISSUE TITLE
Why does chaining in one order work, but not in the other?

### ISSUE THREAD

**Issue by pixelpax** [workshopper/stream-adventure#178]
I am looking at the problem 'http client'

I made the following solution which passes 2/3 tests:

```
request = require 'request'

#Generate a read/writable stream piping into the outbuff
myRequest = request.post("http://localhost:8099").pipe(process.stdout)

process.stdin.pipe(myRequest)
```

...with the following error:

```
    operator: equal
    expected:
      'azzwcc\njup\nvccvwcddun\nmukp\nikeos.\nPaps\'w\nheghuuyuuv\nwu\nbzcawcsenvzm\nouggkneoasc\n'
    actual:
      'allsee\nfor\ndeedsetton\nyour\nquick.\nTark\'s\nbimboowood\nso\npleasekindly\ncommunicake\n'
```

However, when I pipe the output in this order, it works fine. 

```
request = require 'request'

#Generate a read/writable stream piping into the outbuff
myRequest = request.post("http://localhost:8099")

process.stdin.pipe(myRequest).pipe(process.stdout)
```

Shouldn't these two solutions be the same? What am I missing here?

**Comment by CodeMan99** [comment]
The [pipe](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options) method returns the destination stream.

In your first example `myRequest` is set to `process.stdout`. In your second example `myRequest` is set to the return value of `request.post`.

You should be able to do the following:

```javascript
var myRequest = request.post("http://localhost:8099");

myRequest.pipe(processs.stdout);

process.stdin.pipe(myRequest);
```

(Note I didn't actually try the above)

**Comment by ccarruitero** [comment]
closing since the question seems to be resolved
