### ISSUE TITLE
Split not valid for stream3

### ISSUE THREAD

**Issue by mchirlin** [workshopper/stream-adventure#181]
This is in reference to the lines problem.

split is no longer a valid package for splitting a stream3.  Instead, split2 should be used.  View here:
https://github.com/substack/browserify-adventure/pull/26 for a related issue

**Comment by kalinchernev** [comment]
@mchirlin I tested the scenario with `split` and it still works fine, i.e. it doesn't seem a breaking dependency for the moment, but I included a note about that in the problem definition.

Reference example usage of `split` with `through2` which passes:

```
var through = require('through2');
var split = require('split');
var count = 1;

function write(line, _, next) {
  var result = '';

  if (count%2 == 0) {
    result = line.toString().toUpperCase();
  } else {
    result = line.toString().toLowerCase();
  }
  count++;
  
  this.push(result + '\n');
  
  next();
}

function end(done) {
  done();
}

process.stdin.pipe(split()).pipe(through(write, end)).pipe(process.stdout);
```

Is it an ok solution for you for this open issue?

**Comment by ccarruitero** [comment]
I'm closing this, since it's stale from a lot of time ago.
