### ISSUE TITLE
Output detail failure message for Duplexer Redux problem

### ISSUE THREAD

**Issue by letientai299** [workshopper/stream-adventure#183]
- node version: v5.4.1
- npm version: 3.5.3

For **stream-adventure**, Duplexer Redux problem, there should be more detail
error message, instead of just:

```
TAP version 13
# (anonymous)
ok 1 stream-adventure verify YOURFILE.js
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

The following source code is copy from `stream-adventure solution`, and then
remove `{objectMode: true}` in the call of `duplexer(...)`.

``` js
var duplexer = require('duplexer2');
var through = require('through2').obj;

module.exports = function (counter) {
  var counts = {};
  var input = through(write, end);

  return duplexer(input, counter);

  function write(row, _, next) {
    counts[row.country] = (counts[row.country] || 0) + 1;
    next();
  }
  function end(done) {
    counter.setCounts(counts);
    done();
  }
};

```

Which the `opjectMode` option, the code works just fine. But without it, I have
no clue why the code is fail. Also notice that the second test case (
`solution exports a function`) got failed. I believe there's something wrong in
the verification.

**Comment by mn113** [comment]
I get the same error message (with no details included) on Problem 11 - Duplexer.

**Comment by kalinchernev** [comment]
I added a "duplicate" label as there's been discussion and suggestions in #158

**Comment by letientai299** [comment]
Closing this as duplicated with #158
