### ISSUE TITLE
Solution pass without using split module

### ISSUE THREAD

**Issue by chinchaun** [workshopper/stream-adventure#184]
if you use this code the solution is accepted without using  the split module.

var split = require('split'),
    through = require('through2'),
    stream = through(write, end);

var arr = [];
function write(buffer, encoding, next) {
    var strBuff = buffer.toString();
    var result = '';
    if(arr.length % 2 === 0) {
        result = strBuff.toLowerCase();
    }
    else {
        result = strBuff.toUpperCase();
    };
    arr.push(strBuff);
    this.push(result);
    next();
}

function end(done) {
    done();
}

process.stdin.pipe(stream).pipe(process.stdout);

**Comment by kalinchernev** [comment]
Hi @chinchaun what is your suggestion? Update problem description, update tests?

**Comment by chinchaun** [comment]
Hi @kalinchernev my suggestion here is to update the test that verify that the split module is been used

**Comment by kalinchernev** [comment]
@chinchaun digging into this a bit further, it appeared that the `split` module is actually not required, but recommended/suggested. Opened a pull request to clarify that, feel free to feedback on it.

**Comment by chinchaun** [comment]
@kalinchernev you were right it was recommended, i checked you pull request and now is very clear, hi5
