### ISSUE TITLE
Confusion in 'TRANSFORM' Exercise 4

### ISSUE THREAD

**Issue by smp** [workshopper/stream-adventure#185]
Woking through stream-adventure and ran into a variable in the TRANSFORM description that tripped my up a bit. The 'tr' variable isn't used in the description/example text, it is only used in the reference solution _after_ the student completes the exercise. It's not immediately clear what 'tr' represents here:

> Make sure to pipe `process.stdin` into your transform stream
> and pipe your transform stream into `process.stdout`, like this:
> 
> ```
> process.stdin.pipe(tr).pipe(process.stdout);
> ```
> 
> To convert a buffer to a string, call `buffer.toString()`.

Consider updating the 'tr' variable to 'stream' since 'stream' is used in the description/example and runs if the student is following along with the description in their own editor.

**Comment by kalinchernev** [comment]
Related pull requests:
- #163

**Comment by ccarruitero** [comment]
fixed by #163
