### ISSUE TITLE
Change problems to create new folder / files for each problem.

### ISSUE THREAD

**Issue by robbiethegeek** [workshopper/stream-adventure#191]
I submitted a few tiny PRs with tweaks and updates to the problem files, I am happy to do the rest of the problems if there is an agreement that this is ok.  A lot of the nodeschool workshops have been moving to this pattern, and I find that I create a folder in my nodeschool repo so can I go back and reference my solutions as a NodeSchool mentor and organizer.

**Comment by kalinchernev** [comment]
Related pull requests:
- #190
- #189 
- #188

**Comment by ccarruitero** [comment]
Closing since, PRs were merged
