### ISSUE TITLE
bug(websockets): refactor verifying tests or solution

### ISSUE THREAD

**Issue by kalinchernev** [workshopper/stream-adventure#195]
The following issues report same problem:
- #92 (websockets: official solution broken in windows)
- #160 (TypeError: dest.on is not a function)
- #164 (Websockets not passing referenced solutions)
- #174 (WEBSOCKETS Fails verifying)

Pull request #56 seems to be addressing these issues, but probably needs further work and re-roll.

**Comment by ccarruitero** [comment]
Closing since old verify process (`bin/verify`) was replaced with [`adventure-verify`](https://www.npmjs.com/package/adventure-verify) module later. And not we move to use [`workshopper-exercise`](https://www.npmjs.com/package/workshopper-exercise)
