### ISSUE TITLE
duplexer redux Invalid non-string/buffer error

### ISSUE THREAD

**Issue by ghost** [workshopper/stream-adventure#198]
- Related to issue [#158](https://github.com/workshopper/stream-adventure/issues/158)

Using stream-adventure `stream-adventure@4.0.5` and working on workshop 'duplexer redux', im getting the error when trying to run my solution:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
```

This error for this particular workshop has been covered a lot already it seems, however none of the suggested fixes seem to work for me.

Here is my code for reference:

```
var duplexer = require('duplexer2');
var through = require('through2');

module.exports = function (counter) {
  var countries = {};

  function countryCounter (chunk) {
    countries[chunk.country] = (countries[chunk.country] || 0) + 1;
  };
  
  function end() {
    counter.setCounts(countries);
  };
  
  return duplexer(through(countryCounter, end), counter);
}
```

Iv attempted the following fixes:

- Including `{writableObjectMode:true}` in the line where we return the duplex stream
- Including `.obj` in the call to through2
- Including `.obj` in the require of the through2 module
- Including `.obj` in the require of the duplexer2 module

Versions of the various modules iv tried:
- duplexer2@0.0.2
- duplexer2@1.0.4
- through2@2.0.3

The error persists despite any of the above, is there something else im missing? Is my code incorrect, or am i using an incorrect module?

**Comment by AlexHolding** [comment]
This can be closed, i fixed it. For reference it took rewriting the countryCounter function somewhat, i noticed that it wasnt 100% following the signature that through2 prescribes for its transformFunction, that is `function(chunk, encoding, callback)`. I believe missing out the callback meant that the through function couldnt progress properly after it had transformed a chunk of the stream it was consuming. 

I had to add the following to my original code:

```
  function countryCounter (chunk, _, callback) {
    countries[chunk.country] = (countries[chunk.country] || 0) + 1;
    callback();
  };
```

Once i had done this, and added `.obj` to my call to through, as in `return duplexer(through.obj...` then the solution passed.

**Comment by danielmascena** [comment]
If the solution here doesn't work for you, try checking this one [here](https://github.com/workshopper/stream-adventure/issues/158)
