### ISSUE TITLE
Http Server test fails

### ISSUE THREAD

**Issue by sammarder** [workshopper/stream-adventure#199]
I am unable to get the http-server excercise to work, the server only gets 9 words in both my solution and hte one provided. I am trying to figure out how to fix the test on my own and will make something of it once it is fixed.

**Comment by CodeMan99** [comment]
Having the same issue, node v6.13.0. Even the example solution fails.

Note that I cloned this repository (instead of installing from npmjs).

Output of `npm list --depth=0 --production`:

```
stream-adventure@4.1.1 /home/code_m/dev/github.com/workshopper/stream-adventure
├── adventure@2.11.0
├── adventure-verify@2.2.0
├── browserify@13.3.0
├── chunky@0.0.0
├── clone@1.0.3
├── concat-stream@1.6.0
├── duplexer2@0.1.4
├── hyperquest@1.3.0
├── mkdirp@0.5.1
├── optimist@0.6.1
├── osenv@0.1.5
├── provinces@1.8.2
├── request@2.67.0
├── split@1.0.1
├── stream-combiner@0.2.2
├── tar@2.2.1
├── terminal-menu@2.1.1
├── through2@2.0.3
├── trumpet@1.7.2
├── tuple-stream@0.0.2
├── websocket-stream@3.0.1
├── wordwrap@1.0.0
└── x256@0.0.2
```

**Comment by CodeMan99** [comment]
Ref issue #168

**Comment by ccarruitero** [comment]
Closing this, the problem was with verify process, that was replaced to `adventure-verify` later
