### ISSUE TITLE
Refactor adventure to workshopper-adventure

### ISSUE THREAD

**Issue by kalinchernev** [workshopper/stream-adventure#201]
In order to make the workshopper more maintainable, the workshopper runner should be refactored to work with core [workshopper-adventure](https://github.com/workshopper/workshopper-adventure).

**Comment by ccarruitero** [comment]
I'll close this.
We moved to `workshopper-adventure` in https://github.com/workshopper/stream-adventure/commit/5bcf696b7d77d363c584ee1c52577c4c402cf5e0, also problems was refactored to use `workshopper-exercise` in https://github.com/workshopper/stream-adventure/commit/35db979e60172b4573c4a12104e10bd48fcc5b1b
