### ISSUE TITLE
secretz task doesn't work with tar v3

### ISSUE THREAD

**Issue by mserge** [workshopper/stream-adventure#202]
When running node 6 and install tar with default 3 version of tar module you will get 

> var parser = tar.Parse();
>                  ^
> 
> TypeError: Class constructor  cannot be invoked without 'new'
>     at Object.<anonymous> (C:\prj\js\nodeschool\stream-adventure\sol2.js:6:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:393:7)
>     at startup (bootstrap_node.js:150:9)
>     at bootstrap_node.js:508:3

with sample solution.

Sample solution works only with npm install tar@2

**Comment by shokry-suleiman** [comment]
I have same error

**Comment by Yitzi2** [comment]
Same issue for me.  Furthermore, adding the "New" reveals another problem: When it returns on the non-file, that prevents the files inside it from triggering the "on".

**Comment by LohitakshTrehan** [comment]
I have the same issue, i think it has to do something because of the new JS standards and extending classes

**Comment by LinFengYnu** [comment]
This is my solution,you should invoke new and use e.resume()
```
const crypto = require('crypto')
const zlib = require('zlib')
const tar = require('tar')
const concat = require('concat-stream') 

var Parser = tar.Parse
var parser = new Parser()

let cipherName = process.argv[2]
let cipherPassphrase = process.argv[3]

parser.on('entry', function (e) {
    e.resume()
    let hash = crypto.createHash('md5', { encoding: 'hex' })
    e.pipe(hash).pipe(concat((hash)=>{
        console.log(`${hash} ${e.path}`)
    }))
});

// 
process.stdin
.pipe(crypto.createDecipher(cipherName, cipherPassphrase))
.pipe(zlib.createGunzip())
.pipe(parser)

```
