### ISSUE TITLE
Confused by arguments for Duplexer...

### ISSUE THREAD

**Issue by bartonyoung** [workshopper/stream-adventure#205]
I completed the first Duplexer challenge with the following code:

```js
    const duplexer = require('duplexer2')
    const spawn = require('child_process').spawn
    
    module.exports = function (cmd, args) {
  
      const child = spawn(cmd, args)

      return duplexer(child.stdin, child.stdout); 
  
   };

```

But now I am confused because the solution to Duplexer-Redux shows something like

```js
return duplexer({objectMode: true}, writable, readable);
```

I am confused by the first {objectMode: true} argument. How did passing 'child.stdin' as the first argument work even though the docs state that you have to pass an [options] arg?

**Comment by coolaman75** [comment]
Hello bartonyoung, i am a newbie at js too, but i believe that in the docs for duplexer2 the syntax is given as follows : duplexer2([options], writable, readable)
as you can see here the [options] is in square brackets which means this parameter/argument is optional and can be skipped. the same convention is followed in pretty much all the documentation of just about any popular programming languages that is to say that if the parameter/argument is in [squar brackets], it can be skipped.

**Comment by finnp** [comment]
I don't think it should be set on objectMode there. That would mean that the stream allows objects to be piped in it. That doesn't make sense to me though. I proposed to remove it https://github.com/workshopper/stream-adventure/pull/209
