### ISSUE TITLE
installing needs permissions

### ISSUE THREAD

**Issue by shoutoutloud** [workshopper/stream-adventure#207]
Hi, I am new to open source.I have faced an issue that when using the command : npm install -g stream-adventure i got error like this:

npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "stream-adventure"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/stream-adventure
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/stream-adventure'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules/stream-adventure'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/stream-adventure' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/starlord/stream-adv2/npm-debug.log

But when I used "sudo" before the command like : sudo npm install -g stream-adventure
there was no error.
I am using ubuntu 16.04 LTS.
So I was hoping to update README.md for the same.
Will it be useful ?
If yes, please guide me to make it my first contribution.
Thank you.

**Comment by benhalverson** [comment]
You have a permissions issue. sudo is not required to install stream-adventure

**Comment by finnp** [comment]
Have a look at https://www.youtube.com/watch?v=bxvybxYFq2o
