### ISSUE TITLE
Meet pipe - no ok 2 should be equivalent - Errors not clear in this adventure

### ISSUE THREAD

**Issue by kushalmahajan** [workshopper/stream-adventure#216]
Here'e my code 

```
const fs = require('fs');
const file = process.argv[2];

fs.createReadStream(file).pipe(process.stdout);
```
This passes all but one test. Not sure what's wrong. 

Test fails saying - 

> not ok 2 should be equivalent
>   ---
>     operator: deepEqual
>     expected:
>       'Guardian of Time\nDalek/Human hybrid\nNestene Consciousness\nFamily of Blood\nJeggorabax energy entity\nGelth\nTerileptil\nAbaddon\nAdipose\nSkullion\n'
>     actual:
>       ''
>   ...
>

**Comment by colto** [comment]
I also can't seem to get passed lesson 2 without an error.

**Comment by ccarruitero** [comment]
@kushalmahajan seems correct, what version of node and os are you using?
@colto can you solved the problem?

**Comment by ccarruitero** [comment]
I'm closing this since is stale and we don't have too much information for replicate the problem.
