### ISSUE TITLE
Lesson #6 concat output similar but different from verify

### ISSUE THREAD

**Issue by nashikun** [workshopper/stream-adventure#218]
Hello,
so I've been trying to solve this challenge and I cn't manage to solve it. Somehow the output I have is made of real words but there are a few that are different from the verify text. here is my code:
```Javascript
var concat = require('concat-stream');
var tr= process.stdin
    .pipe(concat(function (err, chunk) {
        if (err)
            throw err
        process.stdout.write(chunk.toString().split('').reverse().join(''));
    }))
```

I got the following output: 

> Every conifer in the village
heard the apt clamor from the
town square. Looking zestily
into the distance, Constable
Franklin flipped his digital
periscope to locate the
piercing source. Unwittingly,
a nearby dingo verily
consumed high-velocity
ionizing particles.

while the verify gives me the following:

> Every isotope in the village
heard the unhelpful clamor
from the town square. Looking
unparadoxically into the
distance, Constable Franklin
consumed his confusing
periscope to locate the
piercing source. Unwittingly,
a nearby x-ray zestily
emitted high-velocity apt
particles.

The two are pretty similar, but there are a few words (like "unparadoxically" ) that have no way of appearing in the other one. Am I doing something wrong?

Than you

**Comment by kobecow** [comment]
Did your code run correctly?
I tried your code. It doesn't work.

Then I tried this code below.
`var concat = require('concat-stream');
process.stdin
    .pipe(concat(function (err, chunk) {
        if (err)
            throw err
        process.stdout.write(chunk.toString().split('').reverse().join(''));
    }))`

It ran, But I found out that err statement ran.
So I edited and tried this below 
`var concat = require('concat-stream');
process.stdin
    .pipe(concat(function (chunk) {
        process.stdout.write(chunk.toString().split('').reverse().join(''));
    }));`

I think my answer doesn't suit for your question though.

**Comment by nashikun** [comment]
> Did your code run correctly?
> I tried your code. It doesn't work.
> 
> Then I tried this code below.
> `var concat = require('concat-stream'); process.stdin .pipe(concat(function (err, chunk) { if (err) throw err process.stdout.write(chunk.toString().split('').reverse().join('')); }))`
> 
> It ran, But I found out that err statement ran.
> So I edited and tried this below
> `var concat = require('concat-stream'); process.stdin .pipe(concat(function (chunk) { process.stdout.write(chunk.toString().split('').reverse().join('')); }));`
> 
> I think my answer doesn't suit for your question though.

I solved it, but I'm not quite sure what made it work. I mean, using `(chunk)` instead of `(err, chunk)` might give an error, but I'm unsure how it'll make new words appear out of nowhere. (like 'conifer' or 'digital' for example)

**Comment by kobecow** [comment]
I think it will be help for you.

https://github.com/workshopper/stream-adventure/blob/master/problems/concat/index.js

I'm not good programmer for reading and understanding index.js. But I saw  'conifer' and 'digital' in index.js

**Comment by ccarruitero** [comment]
Closing since question was solved
