### ISSUE TITLE
Update dependency

### ISSUE THREAD

**Issue by huanghe2015** [workshopper/stream-adventure#220]
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing
npm WARN deprecated hoek@2.16.3: The major version is no longer supported

**Comment by ElementKZ** [comment]
got the same problem

**Comment by CorruptComputer** [comment]
According to https://github.com/workshopper/stream-adventure/issues/229#issuecomment-618418648 this has already been fixed.

**Comment by ccarruitero** [comment]
Thanks @CorruptComputer for notice this. Closing
