### ISSUE TITLE
http_server solution gives `(node:15710) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.`

### ISSUE THREAD

**Issue by StudioSpindle** [workshopper/stream-adventure#223]
The solution works.

However the TimoutOverflowWarning is given.

Running:
- node: v10.17.0
- latest version of stream-adventure

**Comment by ccarruitero** [comment]
Hi @StudioSpindle 

We published recently [v4.1.2](https://www.npmjs.com/package/stream-adventure). Please take a look if the error is still present in that version.

**Comment by StudioSpindle** [comment]
@ccarruitero Confirmed the issue again in the old version.

Tested **v4.1.2** and the _TimoutOverflowWarning_ is not showing anymore. 👍

_(Sidenote: It also looks like the output has changed a bit, very nice! Thank you for this nice introduction project 👏 )_
