### ISSUE TITLE
Is this project supported?

### ISSUE THREAD

**Issue by kkomelin** [workshopper/stream-adventure#224]
Last PR sent on Apr 20, 2019.
Last issue closed on Mar 21, 2019.

So, it's 1 year since last meaningful activity.

**Comment by ccarruitero** [comment]
Hi @kkomelin ,

Most of maintainers aren't working actively in this workshop. I'll try to keep an eye on this workshop from now.

If you find something that isn't working, please feel free to open an issue or a PR.

**Comment by kkomelin** [comment]
Thank you @ccarruitero. I will.
