### ISSUE TITLE
Publish v4.1.2

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/stream-adventure#230]
Hi @workshopper/deploy

I was updating `stream-adventure` dependencies and refactored the module to use current workshopper's modules (`workshopper-adventure` and `workshopper-exercise`).

I don't have publish access, so can you publish this new version ([v4.1.2](https://github.com/workshopper/stream-adventure/releases/tag/v4.1.2)) ?

cc @martinheidegger @julianduque

**Comment by martinheidegger** [comment]
I do not have permissions to publish this 😓

**Comment by ccarruitero** [comment]
I just published the new version in npm https://www.npmjs.com/package/stream-adventure
