### ISSUE TITLE
replace split dependency

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/stream-adventure#233]
[split](https://www.npmjs.com/package/split) is mostly deprecated, since don't receive any update some time ago and there repository was [archived](https://github.com/dominictarr/split).

Looking for alternatives, I think we can use [split2](https://www.npmjs.com/package/split2) that is based in split and keep the same api, so the update shouldn't be too problematic.

**Comment by jordanSu** [comment]
@ccarruitero I agree. And a pull request #242 is made to replace split dependency.

In several problem descriptions which are modified (e.g. problems/combiner/problem.md), I use the term "split2" for the module. But when it comes to stream, I still call it "split" stream.
Any advice is appreciated.
