### ISSUE TITLE
update websocket dependency

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/stream-adventure#234]
We are using [`websocket-stream`](https://www.npmjs.com/package/websocket-stream) for the websockets exercise.

But, looking into package's [repository](https://github.com/maxogden/websocket-stream) seems that doesn't have an active maintainer, since there are some pull request that don't receive any answer.

Also, `websocket-stream` uses internally [`ws`](https://www.npmjs.com/package/ws); and `ws` [allow to generate a websocket stream](https://github.com/websockets/ws#use-the-nodejs-streams-api) now.

So, I think we should move to use `ws` directly

**Comment by jordanSu** [comment]
I think it is ok to move to use `ws`.
I start a PR #237,
Please help review and any advice is welcome.
