### ISSUE TITLE
Why does this need to be a duplex

### ISSUE THREAD

**Issue by zwhitchcox** [workshopper/stream-adventure#251]
https://github.com/workshopper/stream-adventure/blob/master/problems/duplexer_redux/solution.js

The writable stream doesn't output anything. I guess I don't understand the point of the duplex in this exercise, and I'm not sure if it's because I'm not understanding the concept or if it is not necessary for it to be a duplex.

**Comment by ccarruitero** [comment]
Hi @zwhitchcox 

The `duplexer-redux` exercise needs some review and improvements.

I believe the point of the exercise was to show how to use multiple stream modules, but you could resolve the exercise just reading the readable stream (`counter`).
