### ISSUE TITLE
cosmetic: IMHO we should adjust some texts

### ISSUE THREAD

**Issue by vbarzana** [workshopper/stream-adventure#259]
In the exercise "READ IT", the text could be replaced from:
`All Readable streams begin in paused mode but can be switched to flowing mode and also can switched back to paused mode.`
to: 
`All Readable streams begin in paused mode but can be switched to flowing mode and also can be switched back to paused mode.`

In the exercise "MEET PIPE", the text could be replaced from: 
 `The pipe method allow you to connect the output of the readable stream as the input of the writable stream`
to 
`The pipe method allows you to connect the output of the readable stream as the input of the writable stream`

I know this is a very small nit, but I am reporting it anyways if you guys find this is not important, please ignore it.

Best regards,
Victor

**Comment by ccarruitero** [comment]
Hi @vbarzana 

Thank for report this, I think your suggestion are correct. Do you mind open a PR adding these changes?

**Comment by vbarzana** [comment]
Hi @ccarruitero, I will try to get there when I have some free time, currently very busy with  my projects.
Regards,
Victor
