### ISSUE TITLE
HTTP SERVER test not working properly

### ISSUE THREAD

**Issue by jocelynlecomte** [workshopper/stream-adventure#45]
While writing my solution, I first wrote some simple code like

``` js
var server = http.createServer(function (req, res) {
    if (req.method === 'POST') { 
        req.pipe(res);
    }
    res.end();
});
```

and, surprisingly, it did pass the test without complaining

**Comment by kalinchernev** [comment]
Tested the snippet of the reported issue, it's not reproducible any more,  #46 being merged.
