### ISSUE TITLE
Issue in problems/duplexer/problem.txt

### ISSUE THREAD

**Issue by joshcanhelp** [workshopper/stream-adventure#55]
This says:

"The duplexer module exports a single function `duplexer(writable, readable)` that joins together a writable stream and readable stream into a single, readable/writable duplex stream."

... but it should be:

"...a single function `duplexer(readable, writable)` that joins ..."

You have the arguments flip-flopped.

**Comment by ralphtheninja** [comment]
@yihangho is correct. This should be closed.

**Comment by kalinchernev** [comment]
Closing as there is also another #127 together with #104
