### ISSUE TITLE
Exercise 7 passes without converting to upper case

### ISSUE THREAD

**Issue by mcsmcs** [workshopper/stream-adventure#67]
Exercise 7 HTTP SERVER will pass without converting the text to upper case.  Also the test data appears to be generated from the user's code (it was also lowercase).

```
var http = require('http');
var fs = require('fs');
var through = require('through');

var server = http.createServer(function(req,res){
    if(req.method === 'POST'){
        req.pipe(through(function(buf){ this.queue(buf); })).pipe(res);
    }
});

server.listen(process.argv[2]);
```
# OUTPUT

ACTUAL                             EXPECTED
---

"with"                             "with"
"the"                              "the"
"original"                         "original"
"sinse"                            "sinse"
"we"                               "we"
"are"                              "are"
"only"                             "only"
"yearning"                         "yearning"
"as"                               "as"
"yet"                              "yet"
"how"                              "how"
"to"                               "to"
"burgeon."                         "burgeon."
"It's"                             "It's"
"meant"                            "meant"
"milliems"                         "milliems"
"of"                               "of"
"centiments"                       "centiments"
"deadlost"                         "deadlost"
"or"                               "or"
""                                 ""
# PASS

Your solution to HTTP SERVER passed!

Here's what the official solution is if you want to compare notes:

```
var http = require('http');
var through = require('through');

var server = http.createServer(function (req, res) {
    if (req.method === 'POST') {
        req.pipe(through(function (buf) {
            this.queue(buf.toString().toUpperCase());
        })).pipe(res);
    }
    else res.end('send me a POST\n');
});
server.listen(parseInt(process.argv[2]));
```

You have 12 challenges left.
Type `stream-adventure` to show the menu.

**Comment by kalinchernev** [comment]
Tested the scenarios and the problem with the test framework seems to be fixed:

Failing test:
```
TAP version 13
# (anonymous)
ok 1 stream-adventure verify YOURFILE.js
not ok 2 should be equal
  ---
    operator: equal
    expected:
      'BURGEON.\nIT\'S\nMEANT\nMILLIEMS\nOF\nCENTIMENTS\nDEADLOST\nOR\nMISLAID\nON\n'
    actual:
      'burgeon.\nIt\'s\nmeant\nmilliems\nof\ncentiments\ndeadlost\nor\nmislaid\non\n'
    at: ConcatStream.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/stream-adventure/node_modules/concat-stream/index.js:36:43)
  ...

1..2
# tests 2
# pass  1
# fail  1

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

Possibly solved in #46
