### ISSUE TITLE
websockets: official solution broken in windows

### ISSUE THREAD

**Issue by funkybaboon** [workshopper/stream-adventure#92]
When I run the official solution 

```
var ws = require('websocket-stream');
var stream = ws('ws://localhost:8000');

stream.end("hello\n");
```

I get this:

```
PS C:\Users\Benni\Documents\nodejs\nodeschool\stream-adventure1> node .\09websockets.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

**Comment by tyoungjr** [comment]
My code is identical to your's and received this error:  Uncaught TypeError: Invalid non-string/buffer chunk on the client. Issue logged with websocket-stream page as the test-client procedures would not work.

**Comment by ccarruitero** [comment]
This problem was because the old verify process (`bin/verify`). That was replaced with [`adventure-verify`](https://www.npmjs.com/package/adventure-verify) module later. And not we move to use [`workshopper-exercise`](https://www.npmjs.com/package/workshopper-exercise)
